# Generated by Django 5.1.3 on 2026-02-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
