# Generated by Django 5.1.3 on 2026-02-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('alert_id', models.CharField(max_length=200, unique=True)),
                ('discovered_at', models.FloatField(blank=True, null=True)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
    ]
